let text=[`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus iaculis molestie magna et cursus. Morbi enim massa, efficitur id finibus eget, vehicula et dolor. Morbi dolor metus, luctus quis laoreet vel, ultrices eu sapien. Sed aliquet eu tortor in dignissim. Duis placerat, augue convallis facilisis lobortis, nulla augue tempus felis, quis tempor dolor nisi ut turpis. Nam lacinia risus id tristique pulvinar. Mauris sollicitudin blandit magna quis tempus. Curabitur interdum sagittis lacus, a finibus ante tristique tristique. Ut elit dui, scelerisque egestas est in, venenatis scelerisque ipsum. Suspendisse potenti.`,

    `Fusce nec aliquam turpis, sit amet efficitur leo. Fusce non gravida massa. Pellentesque rhoncus ultrices ligula, a bibendum enim faucibus vitae. Aenean sem nisi, dictum eget arcu at, rutrum suscipit odio. Nunc ac erat viverra risus facilisis ultrices. Morbi gravida vestibulum elit, non porta lorem consequat vel. Nam sed gravida leo. Vestibulum efficitur maximus pharetra. Sed id nunc leo. Ut sed rutrum est, nec lacinia odio. Vivamus ac mauris dolor. Donec facilisis justo libero, ut porta lectus iaculis eu. Duis finibus, justo eget viverra porttitor, mi enim porta tellus, quis lobortis tellus diam eu mauris.`,
    
    `Integer ac magna ut lorem dignissim blandit. Suspendisse ut facilisis ante. Integer mi ante, ornare eu erat vitae, vulputate efficitur odio. Nunc aliquam egestas imperdiet. In quis ex diam. Vestibulum dapibus, tellus vel commodo posuere, ex augue porttitor nulla, nec gravida nibh leo quis augue. Curabitur eu nibh quis mauris finibus ullamcorper in eu libero. Sed dictum pellentesque nisl at finibus. Praesent dictum leo mi, et consequat lorem tincidunt sed. Fusce eget laoreet est. Ut quis turpis ultricies, molestie nibh vitae, viverra justo. Nulla facilisi. Curabitur metus libero, commodo ac erat quis, condimentum tempor nulla.`
    ,
   ` Curabitur sed sapien eget ex viverra vestibulum vitae nec velit. Vestibulum interdum id augue a accumsan. Suspendisse potenti. Duis non metus non turpis feugiat sodales a eu ex. Maecenas euismod urna id nunc consectetur sollicitudin. Praesent sed vestibulum nulla, vel semper tortor. Sed pellentesque convallis sem, sed iaculis orci vehicula vitae. Pellentesque mi nibh, ornare sit amet nulla eget, malesuada mollis ex. Ut quis pulvinar urna, nec auctor velit.`
    ,
    `Cras eu elit nibh. Nam dapibus sapien in facilisis pellentesque. Nam porttitor commodo est at gravida. Integer sit amet neque vitae velit finibus vehicula sed non odio. Morbi sed dignissim sem. Ut mollis eu sapien et elementum. Morbi varius laoreet tortor, in lacinia est accumsan porttitor. Suspendisse sed arcu ut libero euismod cursus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut tempor ultricies erat, sit amet ultrices orci sollicitudin vitae. Maecenas scelerisque dolor tortor, eu mattis felis accumsan a.`
    ,
    `Etiam ut erat orci. Ut tincidunt enim non dignissim tincidunt. Nam lobortis cursus massa a tincidunt. Fusce semper tempus metus vitae facilisis. Morbi rhoncus ligula eget bibendum fermentum. Nullam pulvinar ac sapien id posuere. Sed porta et lorem accumsan vehicula. Sed posuere quam est, vel semper ex maximus nec. Donec sit amet nibh auctor, suscipit ligula sit amet, tempus turpis. Cras odio dui, fringilla luctus sodales vitae, porta vel nunc.`
    ,
   ` Sed nulla neque, consequat vitae lacus nec, auctor lacinia ipsum. Suspendisse potenti. Fusce facilisis purus sit amet purus tincidunt, eget egestas dui interdum. Nam viverra sapien in sapien porttitor volutpat. Maecenas at est sollicitudin, semper lectus a, efficitur urna. Quisque varius, arcu sed bibendum egestas, turpis odio dapibus dolor, eget pretium libero risus viverra turpis. Mauris sem ante, commodo eu massa ut, sodales pharetra magna. Nulla sodales ullamcorper ultricies. Etiam vestibulum, lorem in finibus suscipit, lacus magna aliquam metus, at faucibus sapien quam sed augue. Suspendisse dignissim molestie sagittis. Suspendisse elit nisl, dictum bibendum vulputate id, maximus malesuada elit. Nunc iaculis, quam non blandit lacinia, diam ipsum fermentum eros, sed dictum nulla elit vel risus. Quisque at molestie dui. Nunc sed velit vestibulum, dapibus purus id, hendrerit elit.`
    ,
   ` Integer et condimentum risus, et ultrices metus. Sed fringilla, lorem ac elementum vulputate, sapien odio malesuada elit, a ultrices tellus quam eget nunc. Ut dapibus velit in porttitor pellentesque. Vestibulum interdum pretium tortor, eget tincidunt eros. Maecenas eu urna lobortis eros iaculis ultrices. Etiam suscipit ex maximus, aliquam neque eu, maximus felis. Curabitur sed felis imperdiet, tristique libero et, fermentum nisl. Suspendisse ullamcorper arcu non quam imperdiet, a dictum sem laoreet.`
    ,
    `Praesent eget finibus diam. Curabitur tincidunt tellus non facilisis egestas. Duis cursus lacinia tincidunt. Nulla vel consequat libero. Sed vel vulputate sapien. Proin sodales ligula eu commodo accumsan. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In at porta augue. Etiam vel turpis tincidunt, pretium leo in, placerat orci. Nullam sed ante scelerisque, malesuada leo et, gravida tortor. Duis rhoncus diam urna, vel finibus libero laoreet eu.`
    ,
    `In elementum nibh risus, vitae dignissim metus suscipit et. Aenean in neque volutpat, aliquet neque vitae, mattis magna. Etiam et placerat erat, a pretium lectus. Morbi auctor auctor turpis. Ut at lectus consequat, gravida urna at, maximus tellus. Fusce mauris ante, malesuada placerat sollicitudin non, finibus a justo. Donec rhoncus dolor eget ultricies congue. Aliquam suscipit augue velit, quis faucibus tortor aliquet vel. Cras bibendum iaculis vestibulum. Nullam ultrices feugiat consequat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus aliquam lectus felis, suscipit tincidunt nisi fermentum posuere. Vestibulum congue sapien at tincidunt tristique. Morbi pretium lectus eu libero vestibulum ultricies. Integer bibendum euismod ipsum eu iaculis. Integer ac est quis lectus condimentum aliquam eget ut leo.`
    ,
    `Nunc tempus pulvinar sapien et mattis. Nunc non nunc auctor, ultrices dolor vitae, condimentum dui. Ut porttitor bibendum tellus, a fermentum risus posuere eget. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas et orci pharetra orci sodales volutpat eget eget nunc. Donec quis lorem efficitur, tempus tortor non, imperdiet nisl. Ut in velit quis quam tristique faucibus eu non enim. Aenean accumsan dolor sed tortor feugiat, vitae posuere lorem accumsan. Aliquam risus ante, mollis et euismod vel, luctus eget turpis. Vestibulum sed mi mi.`
    
    ];
    function paragraphGentrator(){
        let text_content=document.querySelector(".text-content");
        let randomIndex = Math.floor(Math.random() * text.length)
        text_content.textContent=text[randomIndex];
    }